name: Continuous Integration checks

on: push

jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10.x, 12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node JS Installation
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Dependencies Installation
        run: npm ci
      - name: Unit Tests
        run: npx gulp test
      - name: JS Linter
        run: npx gulp lint
      - name: NPM Audit
        run: npm audit --production
